### PR TITLE
Webpack 4

### PR DESCRIPTION
**Pull request by siamalekpour**
Was having issues with exporting the classes from this plugin into other plugins.

### CODE REVIEW

**Comment by silent1mezzo** [comment]
Looks like we need to drop support for Node v4 and v5. That's fine but it also means this PR would bump up the version number to 5.0.0 since that's a backwards incompatible change.

**Comment by siamalekpour** [comment]
What node version are we using on the server right now? my local machine is `v8.9.1`

**Comment by silent1mezzo** [comment]
@siamalekpour you can ssh into the individual boxes via https://github.com/gadventures/precious-frontend/wiki/Common-Support-Issues

2 boxes are at 6.10.3 one box is 6.12.2

**Comment by silent1mezzo** [comment]
Can you update https://github.com/gadventures/gapi-js/blob/master/.travis.yml too so it doesn't fail.

**Comment by siamalekpour** [comment]
Dropped travis tests on v4 and v5. All nice and rebased.

**Comment by thyleung** [comment]
```
/Users/tleung/dev/gapi-js/gapi-js/node_modules/webpack/bin/webpack.js:3
let webpackCliInstalled = false;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by thyleung** [comment]
getting the above error on `npm install`

**Comment by siamalekpour** [comment]
could it be your node version? Can you make sure it's the latest (or I think at least 6)

**Comment by silent1mezzo** [comment]
[Precious: Switch to Webpack 4](https://trello.com/c/2MLUIjXr/479-precious-switch-to-webpack-4)

**Pull request merged**
